name: PR Auto Review

on:
  pull_request:
    types: [opened, synchronize]
  
  # 手動実行も可能
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR番号（手動実行時）'
        required: true
        type: number
      review_type:
        description: 'レビューの深さ'
        required: false
        default: 'detailed'
        type: choice
        options:
          - quick
          - balanced
          - detailed

permissions:
  contents: read
  pull-requests: write

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.pr.outputs.number }}
      type: ${{ steps.pr.outputs.type }}
    steps:
      - name: Determine PR number and settings
        id: pr
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
            echo "type=${{ inputs.review_type }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            # カスタマイズ: 常にdetailedレビューを実行
            echo "type=detailed" >> $GITHUB_OUTPUT
          fi

      - name: Post start message
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ steps.pr.outputs.number }};
            const type = '${{ steps.pr.outputs.type }}';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `🤖 AI Code Review を開始します...\n- Type: ${type}\n- Repository: ${context.repo.repo}`
            });

  # PRレビュー実行
  review:
    needs: trigger-review
    if: always()
    uses: NFTTechnology/NFTT-GitHub-Workflows/.github/workflows/reusable-pr-review.yml@main
    with:
      pr_number: ${{ needs.trigger-review.outputs.number }}
      repository: ${{ github.repository }}
      review_type: ${{ needs.trigger-review.outputs.type }}
      max_diff_lines: 10000
      enable_code_suggestions: true
    secrets: inherit