name: 3AI Issue Analysis

on:
  issue_comment:
    types: [created]

jobs:
  analyze:
    if: startsWith(github.event.comment.body, '/analyze') && github.event.comment.user.login != 'github-actions[bot]'
    uses: ./.github/workflows/reusable-3ai-issue-analyzer-v3.yml
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}
      repository: ${{ github.repository }}
      comment_id: ${{ github.event.comment.id }}
    secrets: inherit