name: Debug 3AI Analyzer

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'Issue number to analyze'
        required: true
        type: number
      issue_title:
        description: 'Issue title'
        required: true
        type: string
      issue_body:
        description: 'Issue body'
        required: true
        type: string
      repository:
        description: 'Repository name (owner/repo)'
        required: true
        type: string
    secrets:
      ANTHROPIC_API_KEY:
        required: true
    outputs:
      result:
        description: 'Debug result'
        value: ${{ jobs.debug.outputs.result }}

jobs:
  debug:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.test.outputs.result }}
    
    steps:
      - name: Debug Test
        id: test
        run: |
          echo "🧪 3AI Debug Test"
          echo "Issue: #${{ inputs.issue_number }} - ${{ inputs.issue_title }}"
          echo "Repository: ${{ inputs.repository }}"
          echo "Body length: ${#issue_body}"
          echo "API Key present: ${{ secrets.ANTHROPIC_API_KEY != '' }}"
          echo "result=debug_success" >> $GITHUB_OUTPUT
        env:
          issue_body: ${{ inputs.issue_body }}