name: Minimal Test

on:
  workflow_call:
    inputs:
      test_input:
        required: true
        type: string
    outputs:
      test_output:
        value: ${{ jobs.test.outputs.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    steps:
      - name: Minimal test
        run: echo "Input: ${{ inputs.test_input }}"
      
      - name: Set output
        id: set-output
        run: echo "result=minimal_success" >> $GITHUB_OUTPUT