name: Test Simple Reusable

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-simple.yml'
      - '.github/workflows/simple-test.yml'

jobs:
  call-simple-test:
    uses: ./.github/workflows/simple-test.yml
    with:
      test_message: "Hello from test workflow"
  
  check-result:
    needs: call-simple-test
    runs-on: ubuntu-latest
    steps:
      - name: Check result
        run: |
          echo "Result: ${{ needs.call-simple-test.outputs.result }}"
          if [ "${{ needs.call-simple-test.outputs.result }}" = "success" ]; then
            echo "✅ シンプルテスト成功"
          else
            echo "❌ シンプルテスト失敗"
            exit 1
          fi