# This is a workflow template for calling the 3AI Issue Analyzer
# Copy this file to your repository's .github/workflows/ directory
# and customize as needed

name: 3AI Issue Analysis

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to analyze'
        required: true
        type: number

jobs:
  analyze-issue:
    if: |
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request == null &&
       contains(github.event.comment.body, '/analyze')) ||
      github.event_name == 'workflow_dispatch'
    uses: NFTTechnology/NFTT-GitHub-Workflows/.github/workflows/reusable-3ai-issue-analyzer.yml@main
    with:
      issue_number: ${{ github.event_name == 'workflow_dispatch' && inputs.issue_number || github.event.issue.number }}
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}
      comment_id: ${{ github.event.comment.id || 0 }}
      repository: ${{ github.repository }}
    secrets: inherit
    permissions:
      issues: write
      contents: read